---
- name: Board
  items:
    Wood: 2

- name: Bucket
  items:
    Wood: 2

- name: Oars
  items:
    Wood: 2
    Board: 1

- name: Resin Float
  items:
    Resin: 1
    Wood: 1

- name: Rope
  items:
    Thread: 2
